version: '2'

services:
  app:
    image: 'jumia_app'
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jumia_app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlite:sample.db
      - SPRING_DATASOURCE_USERNAME=
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
    - 8088:8080
